headers_di_db = '''id serial PRIMARY KEY,
                    portfel varchar(20),
                    Vzyskatel varchar(20),
                    Status varchar(20),
                    v_rabote varchar(20),
                    Ssylka_na_dose varchar(20),
                    FIO varchar(50),
                    Rod varchar(10),
                    Nomer_dogovora varchar(50),
                    Data_nachala varchar(20),
                    Summa_po_resheniju_suda varchar(20),
                    Summa_po_tsessii varchar(20),
                    Ostatok_dolga varchar(20),
                    Platezh varchar(20),
                    Data_posl_platezha varchar(20),
                    Adres_registratsii_Dolzhnika text,
                    KAB text,
                    SROKI varchar(20),
                    Data_opredelenija_o_pravopreemstve varchar(20),
                    Pravopreemstvo_s_otmetkoj varchar(20),
                    Data_poluchenija_ID varchar(20),
                    tip_ID varchar(20),
                    Nomer_dela varchar(20),
                    Data_reshenija varchar(20),
                    Reshenie_s_otmetkoj varchar(20),
                    №_ispolnitelnogo_dokumenta varchar(20),
                    Data_ID varchar(20),
                    Data_predjavlenija_ID varchar(20),
                    Data_vozbuzhdenija_IP varchar(20),
                    Data_okonchanija_IP varchar(20),
                    Dejstvujuschee_IP varchar(60),
                    Ssylka_FSSP varchar(20),
                    Kommentarii_IP varchar(20),
                    sposob_otpravki_narochno_№treka varchar(20),
                    Otslezhivanie_pochtovogo_treka varchar(20),
                    ROSP_Bank text,
                    Bank_UFSSP text,
                    Adres_ROSP_Banka text,
                    SPI text,
                    Nahozhdenie_ID text,
                    Sud text,
                    Adres_suda text,
                    Elektronnyj_adres_suda varchar(20),
                    Sudebnye_kommentarii text,
                    Imuschestvo_dlja_vzyska text,
                    Arest varchar(20),
                    Uvedomlenie varchar(20),
                    Otsenka_ili_vypiska_iz_EGRP varchar(20),
                    Kommentarii_po_vzysku varchar(20),
                    data_postanovki_208 varchar(20),
                    data_ispolnenija_208 varchar(20),
                    data_postanovki_395 varchar(20),
                    data_ispolnenija_395 varchar(20),
                    Dosuzhivanie_data_postanovki varchar(20),
                    Dosuzhivanie_data_ispolnenija varchar(20),
                    Dublikat_data_postanovki varchar(20),
                    Dublikat_data_ispolnenija varchar(20),
                    ISK_data_postanovki varchar(20),
                    ISK_data_ispolnenija varchar(20),
                    SP__data_postanovki varchar(20),
                    SP_data_ispolnenija varchar(20),
                    PP_data_postanovki varchar(20),
                    PP_data_ispolnenija varchar(20),
                    ROSP_zadacha varchar(20),
                    ROSP_data_postanovki varchar(20),
                    ROSP_data_ispolnenija varchar(20),
                    otchet_ROSP varchar(20),
                    Zadacha varchar(20),
                    Data_zadachi varchar(20),
                    Data_ispolnenija_zadachi varchar(20),
                    svodka varchar(20),
                    papka_FSSP varchar(20),
                    MESTO_RABOTY_PO_DANNYM_FSSP text,
                    INN varchar(20),
                    Aktualnyj_telefon varchar(50),
                    Dose varchar(20),
                    adres_papki text,
                    adres_papki_FSSP text,
                    Region_ROSP text,
                    gosposhlina_SP money,
                    gosposhlina_isk money,
                    summa_gosposhliny money,
                    vozvrat_gosposhliny money,
                    mesto_rozhdenija text,
                    Summa_vydannogo_kredita money,
                    srok_kredita varchar(20),
                    stavka_po_kreditu varchar(10),
                    Ostatok_prosrochennoj_zadolzhennosti_po_OD money,
                    Ostatok_prosrochennoj_zadolzhennosti_po_proc money,
                    Neustojka money,
                    Gosposhlina money,
                    Dogovor_tsessii varchar(20),
                    dnej varchar(20),
                    Data_ustupki varchar(20)'''

headers_230522_db = '''id serial PRIMARY KEY,
                    FIO varchar(50),
                    pol varchar(10),
                    DR varchar(20),
                    Pasportnye_dannye text,
                    Nomer_dogovora varchar(20),
                    Data_nachala varchar(20),
                    Summa_po_resheniju_suda float,
                    Summa_po_tsessii float,
                    Adres_registratsii_Dolzhnika text,
                    KAB text'''


'''
Извлечение заголовков столбцов, transliterat кирилицы в латиницу

Полученные заголовки необходимо отформатировать:
- запрещены символы ()/'%
- заменить: / на _
- заменить: % на percent

Формат столбцов:
- текст до 100 символов (в т.ч. даты, ссылки и пр.) --> varchar(100);
- текст более 100 символов --> text;
- суммы --> float. Если данные в float не грузятся, то сначало сделать формат numeric, а затем float;
'''
headers_01122022 = '''id serial PRIMARY KEY,
                    zajavlenie varchar(50),
                    FIO text,
                    pol varchar(50),
                    DR  varchar(50),
                    pensioner varchar(50),
                    z_p varchar(50),
                    Pasportnye_dannye text,
                    Nomer_dogovora varchar(50),
                    Data_nachala varchar(50),
                    Summa_po_resheniju_suda float,
                    Summa_po_tsessii float,
                    Ostatok_dolga float,
                    Platezh float,
                    Data_posl_platezha varchar(50),
                    Adres_registratsii_Dolzhnika text,
                    KAB varchar(50),
                    SROKI varchar(50),
                    Data_opredelenija_o_pravopreemstve varchar(50),
                    Pravopreemstvo_s_otmetkoj varchar(50),
                    Data_poluchenija_ID varchar(50),
                    tip_ID varchar(50),
                    Nomer_dela varchar(50),
                    Data_reshenija varchar(50),
                    Reshenie_s_otmetkoj varchar(50),
                    №_ispolnitelnogo_dokumenta varchar(50),
                    Data_ID varchar(50),
                    Data_predjavlenija_ID varchar(50),
                    Data_vozbuzhdenija_IP varchar(50),
                    Data_okonchanija_IP varchar(50),
                    IP varchar(100),
                    uslovija_okonchanija text,
                    sposob_otpravki varchar(50),
                    Otslezhivanie_pochtovogo_treka varchar(50),
                    ROSP_Bank text,
                    Region_ROSP text,
                    Adres_ROSP text,
                    SPI text,
                    Nahozhdenie_ID text,
                    Sud_po_ID text,
                    Adres_suda text,
                    el_Adres_mir_sud text,
                    Gorodskoj_rajonnyj_sud text,
                    Ostatok_prosrochennoj_zadolzhennosti_po_OD float,
                    Ostatok_prosrochennoj_zadolzhennosti_po_percent float,
                    Neustojka float,
                    percent_na_prosrochennyj_od float,
                    Gosposhlina float'''

# Для функции insert_in_tab()
insert_headers_01122022 = '''
                    zajavlenie,
                    FIO,
                    pol,
                    DR,
                    pensioner,
                    z_p,
                    Pasportnye_dannye,
                    Nomer_dogovora,
                    Data_nachala,
                    Summa_po_resheniju_suda,
                    Summa_po_tsessii,
                    Ostatok_dolga,
                    Platezh,
                    Data_posl_platezha,
                    Adres_registratsii_Dolzhnika,
                    KAB,
                    SROKI,
                    Data_opredelenija_o_pravopreemstve,
                    Pravopreemstvo_s_otmetkoj,
                    Data_poluchenija_ID,
                    tip_ID,
                    Nomer_dela,
                    Data_reshenija,
                    Reshenie_s_otmetkoj,
                    №_ispolnitelnogo_dokumenta,
                    Data_ID,
                    Data_predjavlenija_ID,
                    Data_vozbuzhdenija_IP,
                    Data_okonchanija_IP,
                    IP,
                    uslovija_okonchanija,
                    sposob_otpravki,
                    Otslezhivanie_pochtovogo_treka,
                    ROSP_Bank,
                    Region_ROSP,
                    Adres_ROSP,
                    SPI,
                    Nahozhdenie_ID,
                    Sud_po_ID,
                    Adres_suda,
                    el_Adres_mir_sud,
                    Gorodskoj_rajonnyj_sud,
                    Ostatok_prosrochennoj_zadolzhennosti_po_OD,
                    Ostatok_prosrochennoj_zadolzhennosti_po_percent,
                    Neustojka,
                    percent_na_prosrochennyj_od,
                    Gosposhlina'''

indexes = (("Должник", 3, '', "SELECT FIO, Rod FROM reestr_test_di WHERE id ="),
           ("Остаток_долга", 0, '', "SELECT Ostatok_dolga FROM reestr_test_di WHERE id ="),
           ("№_ИП", 0, '', "SELECT Dejstvujuschee_IP FROM reestr_test_di WHERE id ="),
           ("Суд", 0, 'суд', "SELECT Sud FROM reestr_test_di WHERE id =")
           )


headers_bankrot = '''id serial PRIMARY KEY,
                    Dolzhnik varchar(50),
                    FIO_do_izmenenija varchar(50),
                    Data_rozhdenija varchar(50),
                    Mesto_rozhdenija text,
                    Adres_registratsii text,
                    INN_dolzhnika varchar(20),
                    SNILS_dolzhnika varchar(20),
                    Sudebnoe_proizvodstvo text,
                    №_dela_o_bankrotstvetext varchar(30)'''

